### ISSUE TITLE
Please contact me

### ISSUE THREAD

**Issue by aptajosh** [LEKOSOV/leko#1]
I need some support, I think you are the right candidate, contact me over aptajosh@gmail.com, Thank You!!

**Comment by LEKOSOV** [comment]
Hello. How can I help?

**Comment by aptajosh** [comment]
may I get your email Id? so, we will continue the further conversation on the email.

**Comment by LEKOSOV** [comment]
here it is
lekosovplay@gmail.com

**Comment by aptajosh** [comment]
I just sent the mail, please check and respond, Thank You!!
